name: aws-sns-publish
on: [public]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: sns-message
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: sns publish --message "Hi, The visiblity of your GitHub repository has changed. Please take appropriate action if required. Thanks" --topic-arn "arn:aws:sns:ap-south-1:367382347063:GitHubRepositoryAction" --subject "GitHub repository visibility changed!"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
